TARGET = Zero2Go-Omini.ino
ARDUINO_DIR = /opt/arduino-1.8.10
USER_LIB_PATH = /opt

# Programmer type:
ISP_PROG = usbasp

# https://github.com/SpenceKonde/ATTinyCore (1.5+)
ALTERNATE_CORE = ATTinyCore
ALTERNATE_CORE_PATH = /opt/ATTinyCore
BOARD_TAG = attinyx41
BOARD_SUB = 841
F_CPU = 8000000L

# Path to the Arduino Makefile
include /opt/arduino-mk/Arduino.mk
